# Generated by Django 5.0.6 on 2024-05-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fileInput',
            field=models.ImageField(default='img.jpg', upload_to='uploads/'),
        ),
    ]
